default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: ums2

test:
 <<: *default
 database: ums2_test
